language: node_js
services:
  - docker
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm prune
after_success:
- ./deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
